/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WujieRouteImport } from './routes/wujie'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as QuickjsRouteImport } from './routes/quickjs'
import { Route as JsonJsRouteImport } from './routes/jsonJs'
import { Route as JdmicroRouteImport } from './routes/jdmicro'
import { Route as FlagRouteImport } from './routes/flag'
import { Route as ExcelRouteImport } from './routes/excel'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReactIndexRouteImport } from './routes/react/index'
import { Route as PrintIndexRouteImport } from './routes/print/index'
import { Route as OnlineIndexRouteImport } from './routes/online/index'
import { Route as App1IndexRouteImport } from './routes/app1/index'
import { Route as AppListRouteImport } from './routes/app/list'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as MicroAppIndexRouteImport } from './routes/micro/$app/index'
import { Route as App1AppIndexRouteImport } from './routes/app1/$app/index'
import { Route as AppIdIndexRouteImport } from './routes/app/$id/index'
import { Route as PrintComponentsPrintCoreRouteImport } from './routes/print/components/printCore'
import { Route as PrintComponentsPdfRouteImport } from './routes/print/components/pdf'
import { Route as PrintComponentsHtmlRouteImport } from './routes/print/components/html'
import { Route as PrintComponentsDocxRouteImport } from './routes/print/components/docx'
import { Route as AppIdEditRouteImport } from './routes/app/$id/edit'

const WujieRoute = WujieRouteImport.update({
  id: '/wujie',
  path: '/wujie',
  getParentRoute: () => rootRouteImport,
})
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
})
const QuickjsRoute = QuickjsRouteImport.update({
  id: '/quickjs',
  path: '/quickjs',
  getParentRoute: () => rootRouteImport,
})
const JsonJsRoute = JsonJsRouteImport.update({
  id: '/jsonJs',
  path: '/jsonJs',
  getParentRoute: () => rootRouteImport,
})
const JdmicroRoute = JdmicroRouteImport.update({
  id: '/jdmicro',
  path: '/jdmicro',
  getParentRoute: () => rootRouteImport,
})
const FlagRoute = FlagRouteImport.update({
  id: '/flag',
  path: '/flag',
  getParentRoute: () => rootRouteImport,
})
const ExcelRoute = ExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => rootRouteImport,
})
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const ReactIndexRoute = ReactIndexRouteImport.update({
  id: '/react/',
  path: '/react/',
  getParentRoute: () => rootRouteImport,
})
const PrintIndexRoute = PrintIndexRouteImport.update({
  id: '/print/',
  path: '/print/',
  getParentRoute: () => rootRouteImport,
})
const OnlineIndexRoute = OnlineIndexRouteImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => rootRouteImport,
})
const App1IndexRoute = App1IndexRouteImport.update({
  id: '/app1/',
  path: '/app1/',
  getParentRoute: () => rootRouteImport,
})
const AppListRoute = AppListRouteImport.update({
  id: '/app/list',
  path: '/app/list',
  getParentRoute: () => rootRouteImport,
})
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/app/create',
  path: '/app/create',
  getParentRoute: () => rootRouteImport,
})
const MicroAppIndexRoute = MicroAppIndexRouteImport.update({
  id: '/micro/$app/',
  path: '/micro/$app/',
  getParentRoute: () => rootRouteImport,
})
const App1AppIndexRoute = App1AppIndexRouteImport.update({
  id: '/app1/$app/',
  path: '/app1/$app/',
  getParentRoute: () => rootRouteImport,
})
const AppIdIndexRoute = AppIdIndexRouteImport.update({
  id: '/app/$id/',
  path: '/app/$id/',
  getParentRoute: () => rootRouteImport,
})
const PrintComponentsPrintCoreRoute =
  PrintComponentsPrintCoreRouteImport.update({
    id: '/print/components/printCore',
    path: '/print/components/printCore',
    getParentRoute: () => rootRouteImport,
  })
const PrintComponentsPdfRoute = PrintComponentsPdfRouteImport.update({
  id: '/print/components/pdf',
  path: '/print/components/pdf',
  getParentRoute: () => rootRouteImport,
})
const PrintComponentsHtmlRoute = PrintComponentsHtmlRouteImport.update({
  id: '/print/components/html',
  path: '/print/components/html',
  getParentRoute: () => rootRouteImport,
})
const PrintComponentsDocxRoute = PrintComponentsDocxRouteImport.update({
  id: '/print/components/docx',
  path: '/print/components/docx',
  getParentRoute: () => rootRouteImport,
})
const AppIdEditRoute = AppIdEditRouteImport.update({
  id: '/app/$id/edit',
  path: '/app/$id/edit',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  ExcelRoute: ExcelRoute,
  FlagRoute: FlagRoute,
  JdmicroRoute: JdmicroRoute,
  JsonJsRoute: JsonJsRoute,
  QuickjsRoute: QuickjsRoute,
  ToolsRoute: ToolsRoute,
  WujieRoute: WujieRoute,
  AppCreateRoute: AppCreateRoute,
  AppListRoute: AppListRoute,
  App1IndexRoute: App1IndexRoute,
  OnlineIndexRoute: OnlineIndexRoute,
  PrintIndexRoute: PrintIndexRoute,
  ReactIndexRoute: ReactIndexRoute,
  AppIdEditRoute: AppIdEditRoute,
  PrintComponentsDocxRoute: PrintComponentsDocxRoute,
  PrintComponentsHtmlRoute: PrintComponentsHtmlRoute,
  PrintComponentsPdfRoute: PrintComponentsPdfRoute,
  PrintComponentsPrintCoreRoute: PrintComponentsPrintCoreRoute,
  AppIdIndexRoute: AppIdIndexRoute,
  App1AppIndexRoute: App1AppIndexRoute,
  MicroAppIndexRoute: MicroAppIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
