/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as DocxRouteImport } from './routes/docx'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const DocxRoute = DocxRouteImport.update({
  id: '/docx',
  path: '/docx',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docx': typeof DocxRoute
  '/html': typeof HtmlRoute
  '/pdf': typeof PdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docx': typeof DocxRoute
  '/html': typeof HtmlRoute
  '/pdf': typeof PdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docx': typeof DocxRoute
  '/html': typeof HtmlRoute
  '/pdf': typeof PdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docx' | '/html' | '/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docx' | '/html' | '/pdf'
  id: '__root__' | '/' | '/about' | '/docx' | '/html' | '/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocxRoute: typeof DocxRoute
  HtmlRoute: typeof HtmlRoute
  PdfRoute: typeof PdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docx': {
      id: '/docx'
      path: '/docx'
      fullPath: '/docx'
      preLoaderRoute: typeof DocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocxRoute: DocxRoute,
  HtmlRoute: HtmlRoute,
  PdfRoute: PdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
