/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ReactRouteImport } from './routes/react'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as JsonJsRouteImport } from './routes/jsonJs'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as FlagRouteImport } from './routes/flag'
import { Route as DocxRouteImport } from './routes/docx'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
})
const ReactRoute = ReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => rootRouteImport,
})
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
})
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
})
const JsonJsRoute = JsonJsRouteImport.update({
  id: '/jsonJs',
  path: '/jsonJs',
  getParentRoute: () => rootRouteImport,
})
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
})
const FlagRoute = FlagRouteImport.update({
  id: '/flag',
  path: '/flag',
  getParentRoute: () => rootRouteImport,
})
const DocxRoute = DocxRouteImport.update({
  id: '/docx',
  path: '/docx',
  getParentRoute: () => rootRouteImport,
})
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  DocxRoute: DocxRoute,
  FlagRoute: FlagRoute,
  HtmlRoute: HtmlRoute,
  JsonJsRoute: JsonJsRoute,
  PdfRoute: PdfRoute,
  PrintRoute: PrintRoute,
  ReactRoute: ReactRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
